language: swift
sudo: required
dist: trusty
osx_image: xcode9.2
script:
  - swift build
  - xcodebuild -scheme KKBOXOpenAPISwiftTests test
notifications:
  email:
    on_success: never
    on_failure: change
