language: swift
sudo: required
dist: trusty
osx_image: xcode10.1
before_install:
  - gem install xcov
  - gem update fastlane
script:
  - swift package generate-xcodeproj
  - xcodebuild test -scheme KKBOXOpenAPISwift-Package -enableCodeCoverage YES
  - xcov --scheme KKBOXOpenAPISwift-Package
notifications:
  email:
    on_success: never
    on_failure: change
